package com.project.dao;

import com.project.pojo.Product;
import com.project.pojo.Product;
import org.apache.ibatis.annotations.Param;
import org.springframework.web.bind.annotation.PathVariable;

import java.util.List;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    int insert(Product product);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    List<Product> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Product record);

    /**
     * 修改商品状态
     * @param id
     * @param status
     * @return
     */
    int setSaleStatus(@Param("id") int id, @Param("status")int status);

    /**
     * 查询商品
     * @param productId
     * @param productName
     * @return
     */
    List<Product> findProductByNameAndId(@Param("productId")Integer productId,
                                         @Param("productName")String productName);

    int reduceProductStock(@Param("productId")Integer productId,@Param("stock")Integer stock);

    /**
     * 查询热销商品
     *
     * @return
     */
    List<Product> findHotProduct();
}