package com.project.dao;

import com.project.pojo.User;
import org.apache.ibatis.annotations.Param;
import org.springframework.web.bind.annotation.PathVariable;


import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User record);


    int isExistsUserName(@Param("username")String username);

    int isExistsEmail(@Param("email") String email);

    User findUserByUsernameAndPassword(@Param("username")String username,@Param("password") String password);
    /**
     * 根据username查询密保问题
     */

    public String forget_get_question(@Param("username") String username);
    /**
     * 提交问题答案
     */
    public int forget_check_answer(@Param("username")String username,
                                   @Param("question")String question,
                                   @Param("answer")String answer );
    /**
     * 修改密码
     */
    public int forget_reset_password(@Param("username")String username,
                                     @Param("passwordNew")String passwordNew );


    /**
     * 修改用户信息
     */
    public int updateUserByActive(@Param("user")User user);


}