

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopping?useUnicode=true&characterEncoding=utf-8
    username: hyx
    password: 971208

mybatis:
  mapper-locations: classpath*:com/project/mapper/*Mapper.xml
  type-aliases-package: com.project.pojo


server:
  port: 8080
  servlet:
    context-path: /

